### PR TITLE
fix #265

### LINKED ISSUE #265: reinit!(cellvalues, cell) only works for certain degrees
The following throws an assertion error:
```julia
using JuAFEM

grid = generate_grid(QuadraticLine, (2,))
dim = 1
deg = 1 # deg = 2 is the only value that does not throw
ip = Lagrange{dim, RefCube, deg}()
qr = QuadratureRule{dim, RefCube}(deg+1)
dh = DofHandler(grid)
push!(dh, :u, 1, ip)
close!(dh);
cell = first(CellIterator(dh))
cv = CellScalarValues(qr, ip)
reinit!(cv, cell)
```
```
AssertionError: length(x) == n_geom_basefuncs
```

### PR DESCRIPTION
**Pull request by jw3126**

### CODE REVIEW

**Comment by jw3126** [comment]
CI fail seems unrelated to PR.

File: src/iterators.jl [hunk 1]
```diff
@@ -91,5 +91,23 @@ function reinit!(ci::CellIterator{dim,N}, i::Int) where {dim,N}
...
 end
 
-@inline reinit!(cv::CellValues{dim,T}, ci::CellIterator{dim,N,T}) where {dim,N,T} = reinit!(cv, ci.coords)
-@inline reinit!(fv::FaceValues{dim,T}, ci::CellIterator{dim,N,T}, face::Int) where {dim,N,T} = reinit!(fv, ci.coords, face)
+function check_compatible_geointerpolation(cv::Union{CellValues, FaceValues}, ci::CellIterator)
+    if length(getnodes(ci)) != getngeobasefunctions(cv)
+        msg = """
+        The given CellValues and CellIterator are incompatible. Likely
+        an appropriate geometry interpolate must be passed when constructing
+        the CellValues. See also #265.
```
Comment (KristofferC) [inline src/iterators.jl]: Full link might be better here.
